//Sam Alcosser
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JButton;
import javax.swing.JLabel;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

import java.beans.PropertyChangeListener;
import java.util.Date;
import java.util.List;
import java.beans.PropertyChangeEvent;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import net.miginfocom.swing.MigLayout;
import javax.swing.SwingConstants;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SpringLayout;

public class Homepage {

	JFrame frame;
	 User cUser;
	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			
			
		

			

			public void run() {
				try {
					Homepage window = new Homepage(cUser); 
					window.frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the application. This application gets passed a user object to reference for various functions
	 */
	public Homepage(User cUser) {
		this.cUser = cUser;
		initialize(cUser);
	}

	/**
	 * Initialize the contents of the frame.
	 */
	private void initialize(User cUser) {
		frame = new JFrame();
		frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		frame.getContentPane().setBackground(new Color(0, 191, 255));
		frame.setBounds(100, 100, 448, 303);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		//creating a session factory to connect to the users table through the User mapping class
		SessionFactory factory = new Configuration()
				.configure()
				.addAnnotatedClass(User.class)
				.buildSessionFactory();
		//create session
		Session session = factory.getCurrentSession();
		session.beginTransaction();
		
		JLabel lblNewLabel = new JLabel("Welcome back " + cUser.getUsername().toString());
		lblNewLabel.setHorizontalAlignment(SwingConstants.CENTER);
		lblNewLabel.addPropertyChangeListener(new PropertyChangeListener() {
			public void propertyChange(PropertyChangeEvent evt) {
			
			}
		});
		SpringLayout springLayout = new SpringLayout();
		springLayout.putConstraint(SpringLayout.NORTH, lblNewLabel, 10, SpringLayout.NORTH, frame.getContentPane());
		springLayout.putConstraint(SpringLayout.WEST, lblNewLabel, 88, SpringLayout.WEST, frame.getContentPane());
		frame.getContentPane().setLayout(springLayout);
		frame.getContentPane().add(lblNewLabel);
		
		//*****************************************
		//everything below here was mostly auto-generated by the design interface built into eclipse. notes will be made if anything is custom
		
		JButton btnViewPastWorkouts = new JButton("My Workouts");
		springLayout.putConstraint(SpringLayout.NORTH, btnViewPastWorkouts, 194, SpringLayout.NORTH, frame.getContentPane());
		springLayout.putConstraint(SpringLayout.WEST, btnViewPastWorkouts, 12, SpringLayout.WEST, frame.getContentPane());
		springLayout.putConstraint(SpringLayout.SOUTH, btnViewPastWorkouts, 219, SpringLayout.NORTH, frame.getContentPane());
		springLayout.putConstraint(SpringLayout.EAST, btnViewPastWorkouts, 172, SpringLayout.WEST, frame.getContentPane());
		btnViewPastWorkouts.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {		//simple function to go to see the previous workouts application by passing it the current user, cUser to be used
				frame.setVisible(false);
				PrevWorkouts pW = new PrevWorkouts(cUser);
				pW.frame.setVisible(true);
			}
		});
		frame.getContentPane().add(btnViewPastWorkouts);
		
		JButton btnMyBest = new JButton("My Best");
		btnMyBest.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {	//passing cUser to a metrics frame
				frame.setVisible(false);
				Metrics m = new Metrics(cUser);
				m.frame.setVisible(true);
			}
		});
		springLayout.putConstraint(SpringLayout.NORTH, btnMyBest, 162, SpringLayout.NORTH, frame.getContentPane());
		springLayout.putConstraint(SpringLayout.WEST, btnMyBest, 12, SpringLayout.WEST, frame.getContentPane());
		springLayout.putConstraint(SpringLayout.SOUTH, btnMyBest, 187, SpringLayout.NORTH, frame.getContentPane());
		springLayout.putConstraint(SpringLayout.EAST, btnMyBest, 109, SpringLayout.WEST, frame.getContentPane());
		frame.getContentPane().add(btnMyBest);
		
		
		
		//below is the setup for tracking a new workout. The code here is a bit complex due to the way that workouts are processed
		//before the tracker window is even opened, a new workout is created so that all of the exercises tracked in the next window can 
		//reference the workout just created
		
		
		
		JButton btnTrackNewWorkout = new JButton("Track New Workout");
		springLayout.putConstraint(SpringLayout.SOUTH, lblNewLabel, -57, SpringLayout.NORTH, btnTrackNewWorkout);
		btnTrackNewWorkout.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
			//connecting to the workout table
			SessionFactory fWorkout = new Configuration()
					.configure()
					.addAnnotatedClass(Workout.class)
					.buildSessionFactory();
			//create session
			Session sessionW = fWorkout.getCurrentSession();
			sessionW.beginTransaction();
			Workout nWorkout = new Workout(new Date(),cUser.getId()); 	// making the workout and saving it to the table
			sessionW.save(nWorkout);
			sessionW.getTransaction().commit();
			sessionW.close();
			Tracker track = new Tracker(cUser, nWorkout);
			frame.setVisible(false);
			track.frame.setVisible(true);
			}
		});
		springLayout.putConstraint(SpringLayout.NORTH, btnTrackNewWorkout, 83, SpringLayout.NORTH, frame.getContentPane());
		springLayout.putConstraint(SpringLayout.WEST, btnTrackNewWorkout, 142, SpringLayout.WEST, frame.getContentPane());
		springLayout.putConstraint(SpringLayout.SOUTH, btnTrackNewWorkout, 141, SpringLayout.NORTH, frame.getContentPane());
		springLayout.putConstraint(SpringLayout.EAST, btnTrackNewWorkout, 302, SpringLayout.WEST, frame.getContentPane());
		btnTrackNewWorkout.setForeground(Color.WHITE);
		btnTrackNewWorkout.setBackground(Color.BLACK);
		frame.getContentPane().add(btnTrackNewWorkout);
		
		JList list = new JList();
		springLayout.putConstraint(SpringLayout.EAST, lblNewLabel, -54, SpringLayout.EAST, list);
		springLayout.putConstraint(SpringLayout.NORTH, list, 232, SpringLayout.NORTH, frame.getContentPane());
		springLayout.putConstraint(SpringLayout.WEST, list, 301, SpringLayout.WEST, frame.getContentPane());
		springLayout.putConstraint(SpringLayout.SOUTH, list, 146, SpringLayout.NORTH, frame.getContentPane());
		springLayout.putConstraint(SpringLayout.EAST, list, 390, SpringLayout.WEST, frame.getContentPane());
		frame.getContentPane().add(list);
		
		JButton btnRecordInjury = new JButton("Record Injury");
		btnRecordInjury.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {	//passing cUser to a new injury frame and opening the frame
				Injury Inj = new Injury(cUser);
				frame.setVisible(false);
				Inj.frame.setVisible(true);
				
			}
		});
		springLayout.putConstraint(SpringLayout.NORTH, btnRecordInjury, 195, SpringLayout.NORTH, frame.getContentPane());
		springLayout.putConstraint(SpringLayout.WEST, btnRecordInjury, 273, SpringLayout.WEST, frame.getContentPane());
		springLayout.putConstraint(SpringLayout.EAST, btnRecordInjury, 401, SpringLayout.WEST, frame.getContentPane());
		btnRecordInjury.setBackground(Color.RED);
		frame.getContentPane().add(btnRecordInjury);
		
		JButton btnRemoveInjury = new JButton("remove injury");
		btnRemoveInjury.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) { //function that clears the injury field for the cUser
				
				try {
				List<User> cUsers = session.createQuery("from User u where u.username='"+ cUser.getUsername() + "'").getResultList();
				User uUser = cUsers.get(0);
				uUser.setInjury(null);
				session.update(uUser);
				session.getTransaction().commit();
				}catch(Exception e) {
					JOptionPane.showMessageDialog(frame, "There is no current injury");
				}
			}
		});
		springLayout.putConstraint(SpringLayout.SOUTH, btnRemoveInjury, 0, SpringLayout.SOUTH, btnMyBest);
		springLayout.putConstraint(SpringLayout.EAST, btnRemoveInjury, -47, SpringLayout.EAST, frame.getContentPane());
		frame.getContentPane().add(btnRemoveInjury);
		
		JButton btnNewButton = new JButton("Submit new Exercise");
		springLayout.putConstraint(SpringLayout.WEST, btnNewButton, 0, SpringLayout.WEST, btnTrackNewWorkout);
		springLayout.putConstraint(SpringLayout.SOUTH, btnNewButton, -10, SpringLayout.SOUTH, frame.getContentPane());
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
			SubmitExercise sWorkout = new SubmitExercise(cUser); 	// passing cUser to a new submitExercise frame
			frame.setVisible(false);
			sWorkout.frame.setVisible(true);
			}
		});
		frame.getContentPane().add(btnNewButton);
		
		JButton btnNewButton_1 = new JButton("View Account Info");
		springLayout.putConstraint(SpringLayout.NORTH, btnNewButton_1, 6, SpringLayout.SOUTH, lblNewLabel);
		springLayout.putConstraint(SpringLayout.EAST, btnNewButton_1, 0, SpringLayout.EAST, btnNewButton);
		btnNewButton_1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				AccountInfo acct = new AccountInfo(cUser);	//passing cUser to an account info frame
				frame.setVisible(false);
				acct.frame.setVisible(true);
			}
		});
		frame.getContentPane().add(btnNewButton_1);
	}
}
